
spring:
  application:
    name: auth-service
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
    password: ydea123
    timeout: 5000
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
logging:
  file:
    name: /logs/${spring.application.name}.log
  level:
    com.netflex: warn
    com.tyr: debug
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
feign:
  hystrix:
    enabled: true