server:
  port: 8888
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
  host:
    connect-timeout-millis: 10000
    max-per-route-connections: 10000
    max-total-connections: 10000
    socket-timeout-millis: 3000
  routes:
    api-auth:
      path: /auth/**
      service-id: auth-service
      strip-prefix: true
      sensitive-headers: '*'
    api-business:
      path: /business/**
      service-id: business-service
      strip-prefix: true
      sensitive-headers: '*'
auth-service:
  ribbon:
    listOfServers: http://localhost:9001
business-service:
  ribbon:
    listOfServers: http://localhost:9002 ,http://localhost:9003
ribbon:
  eureka:
    enabled: false
hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 2000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9001/user/current
      id: business
    client:
      client-id: webClient
      client-secret: 654321
      access-token-uri: http://localhost:9001/oauth/token
      grant-type: authorization_code,implicit,password,client_credentials
      scope: all
    authorization:
      check-token-access: http://localhost:9001/oauth/check_token
logging:
  file:
    name: /logs/${spring.application.name}.log
  level:
    com.netflex: warn
    com.tyr: debug
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
swagger:
  butler:
    auto-generate-from-zuul-routes: true
    generate-routes: api-business
    api-docs-path: v2/api-docs
    swagger-version: 2.0