spring:
  application:
    name: center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arcsacy/spring-cloud-config
          search-paths: config-repo
          username: arcsacy
          password: 0Nevergiveup0
          default-label: master
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9000/eureka/
logging:
  file:
    name: /logs/${spring.application.name}.log
  level:
    com.netflex: warn
    com.tyr: debug
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
