spring:
  application:
    name: center
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9000/eureka/
logging:
  file:
    name: /logs/${spring.application.name}.log
  level:
    com.netflex: warn
    com.tyr: debug